sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t peterl732/recruitr -f Dockerfile.dev ./recruitr

script:
  - docker run -e CI=true peterl732/recruitr

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'recruitr-app'
  env: 'Recruitrapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-426715826403'
  bucket_path: 'recruitr-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY